---
kind: pipeline
name: default
type: docker

trigger:
  ref:
    - refs/heads/develop
    - refs/heads/VA-*

steps:
  - name: test
    image: node:latest
    commands:
    - npm install
    - npm test

  - name: deploy
    image: drillster/drone-rsync
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      port: 22
      rm: true
      target: /var/www/webapps/vacms/vacmsapi
      source:
        - ./*
    when:
      branch:
        - develop

  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      script:
        - cp /var/www/envs/vacms/.env.staging /var/www/webapps/vacms/vacmsapi/.env
        - pushd /var/www/webapps/vacms/vacmsapi
        - npm build
        - npm start
    when:
      branch:
        - develop

